Repository VulnerabilityHistoryProject/chromium-vulnerabilities, pull requests merged in 2018-05, with the labels that each got.

#173 CVE-2010-4034 and CVE-2016-1707
  cves/CVE-2010-4034.yml
  cves/CVE-2016-1707.yml
Labels: Cohort D

#179 CVE-2010-4008 and CVE-2014-1748
  cves/CVE-2010-4008.yml
  cves/CVE-2014-1748.yml
Labels: Cohort Q

#176 CVE-2014-1723 & CVE-2016-1660
  cves/CVE-2014-1723.yml
  cves/CVE-2016-1660.yml
Labels: Cohort N

#174 CVE-2010-0664 and CVE-2011-3096
  cves/CVE-2010-0664.yml
  cves/CVE-2011-3096.yml
Labels: Cohort R

#171 CVE-2011-2859 CVE-2016-1628
  cves/CVE-2011-2859.yml
  cves/CVE-2016-1628.yml
Labels: Cohort H

#168 CVE-2010-3252 and CVE-2014-1726
  cves/CVE-2010-3252.yml
  cves/CVE-2011-3925.yml
Labels: Cohort O

#167 CVE-2014-3169 & CVE-2014-1703
  cves/CVE-2014-1703.yml
  cves/CVE-2014-3169.yml
Labels: Cohort P

#166 CVE-2013-2837 & CVE-2016-1657
  cves/CVE-2013-2837.yml
  cves/CVE-2016-1657.yml
Labels: Cohort C

#165 CVE-2010-0663 and CVE-2015-1274
  cves/CVE-2010-0663.yml
  cves/CVE-2015-1274.yml
Labels: Cohort K

#163 CVE-2013-6666 and CVE-2016-1624
  cves/CVE-2013-6666.yml
  cves/CVE-2016-1624.yml
Labels: Cohort I

#162 CVE-2014-1700 and CVE-2009-3934
  cves/CVE-2009-3934.yml
  cves/CVE-2014-1700.yml
Labels: Cohort T

#161 CVE-2011-3961 and CVE-2016-5171
  .DS_Store
  cves/CVE-2011-3961.yml
  cves/CVE-2016-5171.yml
Labels: Cohort S

#158 CVE-2016-5130 and CVE-2016-1679
  cves/CVE-2016-1679.yml
  cves/CVE-2016-5130.yml
Labels: Cohort H
