Repository VulnerabilityHistoryProject/chromium-vulnerabilities, pull requests merged in 2018-07, with the labels that each got.

#156 Started CVE-2015
  cves/CVE-2011-2821.yml
  cves/CVE-2015-1243.yml
Labels: Cohort D

#154 CVE-2013-6653, CVE-2014-3196, CVE-2016-1711
  .gitignore
  cves/CVE-2013-6653.yml
  cves/CVE-2014-3196.yml
  cves/CVE-2016-1711.yml
Labels: Cohort L

#153 CVE-2016-5145 and CVE-2013-0881
  cves/CVE-2013-0881.yml
  cves/CVE-2016-5145.yml
Labels: Cohort P

#152 CVE-2011-3953 and CVE-2016-1697
  cves/CVE-2011-3953.yml
  cves/CVE-2016-1697.yml
Labels: Cohort B

#151 CVE-2010-3251 and CVE-2016-1632
  cves/CVE-2010-3251.yml
  cves/CVE-2016-1632.yml
  cves/CVE-2016-1681.yml
Labels: Cohort E

#149 CVE-2010-1503 and CVE-2013-2845
  cves/CVE-2010-1503.yml
  cves/CVE-2013-2845.yml
Labels: Cohort T

#148 CVE-2016-1635 and CVE-2016-5133
  cves/CVE-2016-1635.yml
  cves/CVE-2016-5133.yml
Labels: Cohort J

#146 CVE-2011-3884 AND CVE-2014-1727
  cves/CVE-2011-3884.yml
  cves/CVE-2014-1727.yml
Labels: Cohort A

#145 CVE-2014-1713 & CVE-2011-2851
  cves/CVE-2011-2851.yml
  cves/CVE-2014-1713.yml
Labels: Cohort A

#144 CVE-2013-0895 and CVE-2016-5137
  cves/CVE-2013-0895.yml
  cves/CVE-2016-5137.yml
Labels: Cohort M

#142 CVE-2015-1293 & CVE-2010-3250
  cves/CVE-2010-3250.yml
  cves/CVE-2015-1293.yml
  cves/CVE-2016-5128.yml
Labels: Cohort L

#141 CVE-2015-1260 and CVE-2014-7934
  cves/CVE-2014-7934.yml
  cves/CVE-2015-1260.yml
Labels: Cohort R

#143 CVE-2014-1715 and CVE-2014-7939
  cves/CVE-2014-1715.yml
  cves/CVE-2014-7939.yml
Labels: Cohort D

#140 CVE-2011-2345 and CVE-2011-2848
  cves/CVE-2011-2345.yml
  cves/CVE-2011-2848.yml
Labels: Cohort E

#139 CVE-2013-6659 and CVE-2014-3157
  cves/CVE-2013-6659.yml
  cves/CVE-2014-3157.yml
Labels: Cohort N

#138 CVE-2016-1693 and CVE-2016-5144
  cves/CVE-2016-1693.yml
  cves/CVE-2016-5144.yml
Labels: Cohort R

#137 CVE-2013-6663 and CVE-2011-2849
  cves/CVE-2011-2849.yml
  cves/CVE-2013-6663.yml
Labels: Cohort G

#134 CVE-2016-1655 & CVE-2010-4485
  cves/CVE-2010-4485.yml
  cves/CVE-2016-1655.yml
Labels: Cohort Q

#133 CVE-2013-0891 and CVE-2014-1732
  cves/CVE-2013-0891.yml
  cves/CVE-2014-1732.yml
Labels: Cohort J

#132 CVE-2015-1216 and CVE-2016-1641
  cves/CVE-2015-1216.yml
  cves/CVE-2016-1641.yml
Labels: Cohort P

#128 CVE-2016-1619, CVE-2015-6755
  cves/CVE-2015-6775.yml
  cves/CVE-2016-1619.yml
Labels: Cohort F

#127 CVE-2015-6765 and CVE-2011-2786
  cves/CVE-2011-2786.yml
  cves/CVE-2015-6765.yml
Labels: Cohort E

#124 CVE-2014-7946 and CVE-2015-6583
  cves/CVE-2014-7946.yml
  cves/CVE-2015-6583.yml
Labels: Cohort I

#123 CVE-2010-4039 and CVE-2014-1714
  cves/CVE-2010-4039.yml
  cves/CVE-2014-1714.yml
Labels: Cohort L

#122 CVE-2016-1647 and CVE-2016-1671
  cves/CVE-2016-1647.yml
  cves/CVE-2016-1671.yml
Labels: Cohort C

#121 CVE-2015-6786 and CVE-2015-6790
  cves/CVE-2015-6786.yml
  cves/CVE-2015-6790.yml
Labels: Cohort G

#120 CVE-2011-2834 and CVE-2014-9646
  cves/CVE-2011-2834.yml
  cves/CVE-2013-6645.yml
Labels: Cohort O

#119 CVE-2014-3156 and CVE-2013-6655
  cves/CVE-2011-3965.yml
  cves/CVE-2013-6655.yml
  cves/CVE-2014-3156.yml
Labels: Cohort K, needs work

#117 CVE-2013-2900 and CVE-2014-7926
  cves/CVE-2013-2900.yml
  cves/CVE-2014-7926.yml
  cves/CVE-2015-6792.yml
Labels: Cohort M
