Repository VulnerabilityHistoryProject/chromium-vulnerabilities, pull requests merged in 2018-10, with the labels that each got.

#175 CVE-2016-1700 and CVE-2015-1210
  cves/CVE-2015-1210.yml
  cves/CVE-2016-1700.yml
Labels: Cohort S, needs work

#170 CVE-2014-1741 and CVE-2016-1636
  cves/CVE-2014-1741.yml
  cves/CVE-2016-1636.yml
Labels: Cohort O, needs work

#164 CVE-2011-3898 and CVE-2015-1257
  cves/CVE-2011-3898.yml
  cves/CVE-2015-1257.yml
Labels: Cohort B, needs work

#157 CVE-2016-5134 and CVE-2011-2787
  cves/CVE-2011-2787.yml
  cves/CVE-2016-5134.yml
Labels: Cohort S, needs work

#136 Initial commit of CVEs 2010-4488 & 2014-7937
  cves/CVE-2010-4488.yml
  cves/CVE-2014-7937.yml
Labels: Cohort T, needs work

#116 CVE-2016-1661 & CVE-2013-6635
  cves/CVE-2013-6635.yml
  cves/CVE-2016-1661.yml
Labels: Cohort C, needs work

#115 Worked on 2011-1812 and 2015-1252
  cves/CVE-2011-1812.yml
  cves/CVE-2015-1252.yml
  cves/CVE-2015-6765.yml
Labels: needs work
