Repository VulnerabilityHistoryProject/chromium-vulnerabilities, pull requests merged in 2019-02, with the labels that each got.

#256 CVE-2014-7925 & CVE-2011-3880
  commits/gitlog.json
  cves/CVE-2011-3880.yml
  cves/CVE-2014-7925.yml
Labels: Cohort B, meneely

#258 CVE-2015-6774 and CVE-2011-3964
  cves/CVE-2011-3964.yml
  cves/CVE-2015-6774.yml
Labels: Cohort M, murukannaiah

#255 CVE-2016-1656 and CVE-2014-7929
  cves/CVE-2014-7929.yml
  cves/CVE-2016-1656.yml
Labels: Cohort N, murukannaiah

#253 CVE-2010-3411 and CVE-2010-0643
  cves/CVE-2010-0643.yml
  cves/CVE-2010-3411.yml
Labels: Cohort P, murukannaiah

#251 CVE-2015-6768 and CVE-2016-5156
  cves/CVE-2015-6768.yml
  cves/CVE-2016-5156.yml
Labels: Cohort N, murukannaiah

#249 CVE-2011-1817 and CVE-2011-2864
  cves/CVE-2011-1817.yml
  cves/CVE-2011-2864.yml
Labels: Cohort T, murukannaiah

#248 CVE-2014-3154 and CVE-2010-3118
  cves/CVE-2010-3118.yml
  cves/CVE-2014-3154.yml
Labels: Cohort C, meneely

#254 CVE-2013-6658 and CVE-2016-5174
  cves/CVE-2013-6658.yml
  cves/CVE-2016-5174.yml
Labels: Cohort L, murukannaiah

#252 CVE-2014-1726 and CVE-2014-7923
  cves/CVE-2014-1726.yml
  cves/CVE-2014-7923.yml
Labels: Cohort U, murukannaiah

#247 Initial YML Changes
  cves/CVE-2013-2875.yml
  cves/CVE-2015-1228.yml
  cves/CVE-2016-5151.yml
Labels: Cohort K, murukannaiah

#246 CVE-2013-6643 and CVE-2015-1272
  cves/CVE-2013-6643.yml
  cves/CVE-2015-1272.yml
Labels: Cohort T, murukannaiah

#245 CVE-2011-1465 and CVE-2014-3159
  cves/CVE-2011-1465.yml
  cves/CVE-2014-3159.yml
Labels: Cohort M, murukannaiah

#244 CVE-2015-6767 and CVE-2015-6782
  cves/CVE-2015-6767.yml
  cves/CVE-2015-6782.yml
Labels: Cohort Q, murukannaiah

#243 CVE-2014-7935 and CVE-2013-2858
  cves/CVE-2013-2858.yml
  cves/CVE-2014-7935.yml
Labels: Cohort W, murukannaiah

#242 CVE-2014-7932 and CVE-2013-0907
  cves/CVE-2013-0907.yml
  cves/CVE-2014-7932.yml
Labels: Cohort W, murukannaiah

#241 CVE-2010-0660 and CVE-2016-1631
  cves/CVE-2010-0660.yml
  cves/CVE-2016-1631.yml
Labels: Cohort K, murukannaiah

#240 CVE-2010-3117 and CVE-2011-0776
  cves/CVE-2010-3117.yml
  cves/CVE-2011-0776.yml
Labels: Cohort O, murukannaiah

#239 CVE-2013-0843 and CVE-2016-1698
  cves/CVE-2013-0843.yml
  cves/CVE-2013-6630.yml
  cves/CVE-2016-1698.yml
Labels: Cohort O, murukannaiah

#238 CVE-2010-4575 and CVE-2012-5154
  cves/CVE-2010-4575.yml
  cves/CVE-2012-5154.yml
Labels: Cohort P, murukannaiah

#237 CVE-2011-1059 and CVE-2011-2845
  cves/CVE-2011-1059.yml
  cves/CVE-2011-2845.yml
Labels: Cohort R, murukannaiah

#236 CVE 2011-1434 and CVE 2015-6769
  cves/CVE-2011-1434.yml
  cves/CVE-2015-6769.yml
Labels: Cohort O, murukannaiah

#235 CVE-2009-1412 and CVE-2014-1743
  cves/CVE-2009-1412.yml
  cves/CVE-2014-1743.yml
Labels: Cohort S, murukannaiah

#234 CVE-2013-6627 and CVE-2015-1221
  cves/CVE-2013-6627.yml
  cves/CVE-2015-1221.yml
Labels: Cohort N, murukannaiah

#233 CVE-2010-0644 and CVE-2014-9689
  cves/CVE-2010-0644.yml
  cves/CVE-2014-9689.yml
Labels: Cohort V, murukannaiah

#232 CVE-2016-5131 and CVE-2016-5139
  cves/CVE-2016-5131.yml
  cves/CVE-2016-5139.yml
Labels: Cohort Q, murukannaiah

#231 CVE-2015-1266 and CVE-2015-6788
  cves/CVE-2015-1266.yml
  cves/CVE-2015-6788.yml
Labels: Cohort R, murukannaiah

#229 CVE-2016-1648 and CVE-2013-2879
  cves/CVE-2013-2879.yml
  cves/CVE-2016-1648.yml
Labels: Cohort U, murukannaiah

#227 CVE-2016-1640 and CVE-2011-3965
  cves/CVE-2011-3965.yml
  cves/CVE-2016-1640.yml
Labels: Cohort Q, murukannaiah

#226 CVE-2015-1258 and CVE-2016-1634
  cves/CVE-2015-1258.yml
  cves/CVE-2016-1634.yml
Labels: Cohort S, murukannaiah

#225 CVE-2015-1252, CVE-2015-1361
  cves/CVE-2015-1252.yml
  cves/CVE-2015-1361.yml
Labels: Cohort V, murukannaiah

#224 Kimberly Sookoo -- CVE-2011-3094 and CVE-2014-1701
  cves/CVE-2011-3094.yml
  cves/CVE-2014-1701.yml
Labels: Cohort I, meneely

#223 CVE-2010-3413 and CVE-2014-7924
  cves/CVE-2010-3413.yml
  cves/CVE-2011-1443.yml
  cves/CVE-2014-7924.yml
Labels: Cohort S, murukannaiah

#222 CVE-2015-1234 and CVE-2016-5149
  cves/CVE-2015-1234.yml
  cves/CVE-2016-5149.yml
Labels: Cohort W, murukannaiah

#221 CVE-2014-1745 and CVE-2015-3334
  cves/CVE-2014-1745.yml
  cves/CVE-2015-3334.yml
Labels: Cohort U, murukannaiah

#220 CVE-2011-3026 and CVE-2016-1617
  cves/CVE-2011-3026.yml
  cves/CVE-2016-1617.yml
Labels: Cohort L, murukannaiah

#219 CVE-2011-1813 and CVE-2016-1633
  cves/CVE-2011-1813.yml
  cves/CVE-2016-1633.yml
Labels: Cohort T, murukannaiah

#217 CVE-2011-2850 and CVE-2013-6628
  cves/CVE-2011-2850.yml
  cves/CVE-2013-6628.yml
Labels: Cohort F, meneely

#216 CVE-2010-4484 and CVE-2014-7948
  cves/CVE-2010-4484.yml
  cves/CVE-2014-7948.yml
Labels: Cohort A, meneely

#215 CVE-2014-1733 and CVE-2013-2839
  cves/CVE-2013-2839.yml
  cves/CVE-2014-1733.yml
Labels: Cohort D, meneely

#214 CVE-2015-6766 and CVE-2014-3161
  cves/CVE-2014-3161.yml
  cves/CVE-2015-6766.yml
Labels: Cohort D, meneely

#213 CVE-2015-6789 and CVE-2016-1706
  cves/CVE-2015-6789.yml
  cves/CVE-2016-1706.yml
Labels: Cohort C, meneely

#212 CVE-2009-2060 and CVE-2011-1305
  cves/CVE-2009-2060.yml
  cves/CVE-2011-1305.yml
Labels: Cohort E, meneely

#211 CVE-2011-1439 and CVE-2011-2837
  cves/CVE-2011-1439.yml
  cves/CVE-2011-2837.yml
Labels: Cohort G, meneely

#210 CVE-2016-5150 and CVE-2014-7930
  cves/CVE-2014-7930.yml
  cves/CVE-2016-5150.yml
Labels: Cohort A, meneely

#209 CVE-2010-1231 and CVE-2013-6656
  cves/CVE-2010-1231.yml
  cves/CVE-2013-6656.yml
Labels: Cohort B, meneely

#208 CVE-2014-1746 and CVE-2016-1616
  cves/CVE-2014-1746.yml
  cves/CVE-2016-1616.yml
Labels: Cohort G, meneely

#207 CVE-2015-6780
  cves/CVE-2015-6780.yml
Labels: Cohort F, meneely

#206 CVE-2014-3166
  cves/CVE-2014-3166.yml
Labels: Cohort F, meneely

#205 CVE-2010-2108 and CVE-2013-0841
  cves/CVE-2010-2108.yml
  cves/CVE-2013-0841.yml
Labels: Cohort G, meneely

#204 CVE-2010-4033 and CVE-2013-6660
  cves/CVE-2010-4033.yml
  cves/CVE-2013-6660.yml
Labels: Cohort F, meneely

#201 CVE-2011-1435 and CVE-2016-1623
  cves/CVE-2011-1435.yml
  cves/CVE-2016-1623.yml
Labels: Cohort K, murukannaiah

#200 CVE-2014-3189 and CVE-2015-1255
  cves/CVE-2014-3189.yml
  cves/CVE-2015-1255.yml
Labels: Cohort I, Exemplary Work, meneely

#199 CVE-2010-1505 and CVE-2014-3191
  cves/CVE-2010-1505.yml
  cves/CVE-2013-2873.yml
  cves/CVE-2014-3191.yml
  cves/CVE-2016-5163.yml
Labels: Cohort C, Exemplary Work, meneely

#198 CVE-2013-6624 and CVE-2016-1687
  cves/CVE-2013-6624.yml
  cves/CVE-2016-1687.yml
Labels: Cohort H, meneely

#197 CVE-2013-0887 and CVE-2014-3201
  cves/CVE-2013-0887.yml
  cves/CVE-2014-3201.yml
Labels: Cohort I, meneely

#196 CVE-2016-1630 and CVE-2016-1652
  cves/CVE-2016-1630.yml
  cves/CVE-2016-1652.yml
Labels: Cohort A, meneely

#195 CVE-2013-0831 and CVE-2015-6781
  cves/CVE-2013-0831.yml
  cves/CVE-2015-6781.yml
Labels: Cohort E, meneely

#193 CVE-2015-1237 and CVE-2015-6762
  cves/CVE-2015-1237.yml
  cves/CVE-2015-6762.yml
Labels: Cohort E, meneely

#192 CVE-2011-0485 and CVE-2014-1747
  cves/CVE-2011-0485.yml
  cves/CVE-2014-1747.yml
Labels: Cohort H, meneely

#191 CVE-2015-1240 & CVE-2016-1686
  cves/CVE-2015-1240.yml
  cves/CVE-2015-1288.yml
  cves/CVE-2016-1686.yml
Labels: Cohort P, murukannaiah

#190 CVE-2016-1682 and CVE-2013-0925
  cves/CVE-2013-0925.yml
  cves/CVE-2016-1682.yml
Labels: Cohort J, meneely

#189 CVE-2016-1675 and CVE-2014-7936
  cves/.CVE-2016-1675.yml.swp
  cves/CVE-2014-7936.yml
  cves/CVE-2016-1675.yml
  cves/CVE-2016-1702.yml
Labels: Cohort H, meneely

#188 CVE-2014-1744 and CVE-2013-2844
  cves/CVE-2013-2844.yml
  cves/CVE-2014-1744.yml
Labels: Cohort V, murukannaiah

#187 CVE 2011-1113 and CVE 2010-1504
  cves/CVE-2010-1504.yml
  cves/CVE-2011-1113.yml
Labels: Cohort M, murukannaiah

#186 CVE-2014-7941 and CVE-2011-5319
  cves/CVE-2011-5319.yml
  cves/CVE-2014-7941.yml
Labels: Cohort J, meneely
