Repository VulnerabilityHistoryProject/chromium-vulnerabilities, pull requests merged in 2020-02, with the labels that each got.

#315 CVE-2016-5127
  cves/CVE-2016-5127.yml
Labels: Cohort H

#314 CVE-2010-0656 and CVE-2013-6657
  cves/CVE-2010-0656.yml
  cves/CVE-2013-6657.yml
Labels: Cohort O

#313 CVE-2015-1224
  cves/CVE-2015-1224.yml
Labels: Cohort M

#311 CVE-2010-4205 and CVE-2013-2855
  cves/CVE-2010-4205.yml
  cves/CVE-2013-2855.yml
Labels: Cohort Q

#310 CVE-2017-15405
  cves/CVE-2017-15405.yml
Labels: Cohort L

#309 CVE-2017-5109
  cves/CVE-2017-5109.yml
Labels: Cohort J

#308 CVE-2011-0470 and CVE-2015-6755
  cves/CVE-2011-0470.yml
  cves/CVE-2015-6755.yml
Labels: Cohort S

#306 CVE-2015-6779 and CVE-2016-1689
  cves/CVE-2015-6779.yml
  cves/CVE-2016-1689.yml
Labels: Cohort P

#305 Adding to CVE-2017-5110
  cves/CVE-2017-5110.yml
Labels: Cohort C

#304 cve-2010-3415 and cve-2017-5038
  cves/CVE-2010-3415.yml
  cves/CVE-2017-5038.yml
Labels: Cohort R

#303 CVE-2016-7549 and CVE-2011-1108
  cves/CVE-2011-1108.yml
  cves/CVE-2016-7549.yml
Labels: Cohort L

#302 CVE-2011-1196
  cves/CVE-2011-1196.yml
Labels: Cohort K

#301 CVE-2011-1198
  cves/CVE-2011-1198.yml
Labels: Cohort M

#300 CVE-2016-5166 and CVE-2011-2782
  cves/CVE-2011-2782.yml
  cves/CVE-2016-5166.yml
Labels: Cohort Q

#299 CVE-2015-1241
  cves/CVE-2015-1241.yml
Labels: Cohort I

#297 CVE-2010-4494 and CVE-2011-2835
  cves/CVE-2010-4494.yml
  cves/CVE-2011-2835.yml
Labels: Cohort S

#296 CVE-2015-1281
  cves/CVE-2015-1281.yml
Labels: Cohort B

#295 CVE-2011-2858 and CVE-2015-1209
  cves/CVE-2011-2858.yml
  cves/CVE-2015-1209.yml
Labels: Cohort K

#294 CVE-2008-6998 updated all the fields
  cves/CVE-2008-6998.yml
Labels: Cohort E

#293 CVE-2015-1292 and CVE-2014-7908
  cves/CVE-2014-7908.yml
  cves/CVE-2015-1292.yml
Labels: Cohort Q

#291 CVE-2010-4574 and CVE-2015-6757
  cves/CVE-2010-4574.yml
  cves/CVE-2015-6757.yml
Labels: Cohort U

#290 CVE-2011-0784
  cves/CVE-2011-0784.yml
Labels: Cohort L

#289 CVE-2010-2653
  cves/CVE-2010-2652.yml
Labels: Cohort I

#287 CVE 2015-1282
  cves/CVE-2015-1282.yml
Labels: Cohort E

#284 CVE-2015-1222
  cves/CVE-2015-1222.yml
Labels: Cohort A

#282 CVE-2017-5093
  cves/CVE-2017-5093.yml
Labels: Cohort O

#281 CVE-2010-4490 and CVE-2010-3247
  cves/CVE-2010-3247.yml
  cves/CVE-2010-4490.yml
Labels: Cohort N

#285 CVE-2016-5173
  cves/CVE-2016-5173.yml
Labels: Cohort O

#283 CVE-2011-1413
  cves/CVE-2011-1413.yml
Labels: Cohort G

#278 CVE-2016-5132
  cves/CVE-2016-5132.yml
Labels: Cohort A
